// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8tYgGvbO-7SuBY--gaDTobYTg8aZQMk',
    appId: '1:307255061308:web:f384a5a969aae28c480c39',
    messagingSenderId: '307255061308',
    projectId: 'emark-b938e',
    authDomain: 'emark-b938e.firebaseapp.com',
    storageBucket: 'emark-b938e.appspot.com',
    measurementId: 'G-GLW6K29JH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuamM-yJHlTSQ1SZcTfoqIh9zc4ge2r5s',
    appId: '1:307255061308:android:33407d117aa3d451480c39',
    messagingSenderId: '307255061308',
    projectId: 'emark-b938e',
    storageBucket: 'emark-b938e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQHjdCdmatUhz2vMaNuPNVtLGkKgV4ww',
    appId: '1:307255061308:ios:dbc404a812e2a329480c39',
    messagingSenderId: '307255061308',
    projectId: 'emark-b938e',
    storageBucket: 'emark-b938e.appspot.com',
    iosBundleId: 'com.example.emark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQHjdCdmatUhz2vMaNuPNVtLGkKgV4ww',
    appId: '1:307255061308:ios:ae92f8a134feed7d480c39',
    messagingSenderId: '307255061308',
    projectId: 'emark-b938e',
    storageBucket: 'emark-b938e.appspot.com',
    iosBundleId: 'com.example.emark.RunnerTests',
  );
}
